language: python

install:
  - pip install sphinx pandas

script:
  # Make the Sphinx HTML, changes to docs directory
  - make -C docs html
  # Tell GitHub not to use jekyll to compile the docs
  - touch docs/_build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch
# of your GitHub repository.
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: gh-pages
  local-dir: docs/_build/html/
  on:
    branch: docs-fix
